#
# Site settings
#
remote_theme: LeakyAbstractions/pretty-docs
url: https://leakyabstractions.github.io
baseurl: /RSMVU
title: &site_title RSM at the VU
description: &site_description Guidance for all your research software development and maintenance
branding:
  icon:
    name: icon_documents_alt
  highlight: RSM
  bold: '@VU'
markdown: kramdown
kramdown:
  auto_ids: true
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  input: GFM
  hard_wrap: false
  footnote_nr: 1
  parse_block_html: true


#
# Owner
#
owner:
  name: Guillermo Calvo
  twitter: &site_owner_twitter gcalvo
  copyright:
    notice: Lorem Ipsum
    author: "[Guillermo Calvo](https://guillermo.in/)"



# Google Analytics
google_analytics: UA-61670496-5


#
# Collections
#
collections:
  doc:
    output: true
    permalink: /:path.html


#
# Default values
#
defaults:
  -
    scope:
      path: ""
      type: doc
    values:
      layout: doc
  -
    scope:
      path: ""
      type: pages
    values:
      layout: doc
