#
# Site settings
#
remote_theme: LeakyAbstractions/pretty-docs
url: https://vu.nl
baseurl: /meronvermaas
title: &site_title VU brings RSM to you
description: &site_description VU brings RSM to you
branding:
  icon:
    name: icon_documents_alt
  highlight: Pretty
  bold: Docs
markdown: kramdown
kramdown:
  auto_ids: true
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  input: GFM
  hard_wrap: false
  footnote_nr: 1
  parse_block_html: true


#
# Owner
#
owner:
  name: VU RDS
  twitter: &site_owner_twitter VU_RDS
  copyright:
    notice: Lorem Ipsum
    author: "[VU](https://vu.nl/nl/medewerker/research-data-support)"


#
# Social
#
open_graph:
  title: *site_title
  site_name: *site_title
  description: *site_description
  locale: en_US
  image: /assets/images/thumb.png
twitter_cards:
  title: *site_title
  description: *site_description
  creator: *site_owner_twitter
  card: summary_large_image
  image: /assets/images/thumb.png
share:
  facebook:
    class: fb-like
    action: like
    layout: button_count
    show-faces: false
    share: false
  twitter:
    via: *site_owner_twitter
    text: &site_description
    title: Tweet
  github:
    repo: meronvermaas/pretty-docs
    position: right
    color: red


# Google Analytics
google_analytics: UA-61670496-5


#
# Collections
#
collections:
  doc:
    output: true
    permalink: /:path.html


#
# Default values
#
defaults:
  -
    scope:
      path: ""
      type: doc
    values:
      layout: doc
  -
    scope:
      path: ""
      type: pages
    values:
      layout: doc
